export const ADD_PAGE = "ADD_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const UPDATE_CURR_PAGE = "UPDATE_CURR_PAGE";
export const UPDATE_PAGE_ORDER = "UPDATE_PAGE_ORDER";
export const UPDATE_PAGE_BACKGROUND = "UPDATE_PAGE_BACKGROUND";
export const UPDATE_BUTTON_FONT_SIZE = "UPDATE_BUTTON_FONT_SIZE";
export const UPDATE_BUTTON_FONT_COLOR = "UPDATE_BUTTON_FONT_COLOR";
export const UPDATE_BUTTON_BG_COLOR = "UPDATE_BUTTON_BG_COLOR";
