export const ADD_PAGE = "ADD_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const UPDATE_CURR_PAGE = "UPDATE_CURR_PAGE";
export const UPDATE_PAGE_ORDER = "UPDATE_PAGE_ORDER";
export const UPDATE_PAGE_BACKGROUND = "UPDATE_PAGE_BACKGROUND";
